name: Deploy Application

on:
  workflow_call:
    inputs:
      triggered_by:
        description: 'Triggered by governance workflow'
        type: string
        required: false
        default: 'manual'
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Triggered by governance workflow'
        type: string
        required: false
        default: 'manual'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy Application
      run: echo "DEPLOYING application"
