name: Production Release

on:
  workflow_dispatch:
    inputs:
      downtime:
        description: 'Does this change cause downtime?'
        type: boolean
        required: true
        default: false
      pii_changes:
        description: 'Does this change affect PII data?'
        type: boolean
        required: true
        default: false
      change_request:
        description: 'Change Request # (required if major release)'
        type: string
        required: false
        default: ''
      tests_verified:
        description: 'I confirm: Tests passed, Sonar passed, changes verified'
        type: boolean
        required: true
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # GOVERNANCE GATE - ALL TEAMS ADD THIS STEP
    - name: Release Governance Check
      uses: ./  # Use your-org/actions/release-governance@v1
      with:
        downtime: ${{ github.event.inputs.downtime }}
        pii-changes: ${{ github.event.inputs.pii_changes }}
        change-request: ${{ github.event.inputs.change_request }}
        tests-verified: ${{ github.event.inputs.tests_verified }}
    
    # TEAM'S EXISTING DEPLOYMENT - UNCHANGED
    - name: Deploy Application
      run: |
        echo "🚀 Deploying application..."
        # Team's existing deployment commands:
        # docker build -t myapp:${{ github.sha }} .
        # docker push myapp:${{ github.sha }}
        # kubectl set image deployment/myapp myapp=myapp:${{ github.sha }}
        # kubectl rollout status deployment/myapp
    
    - name: Verify Deployment
      run: |
        echo "✅ Running health checks..."
        # Team's existing verification:
        # curl -f https://myapp.com/health
        # kubectl get pods -l app=myapp
    
    # OPTIONAL: CREATE AUDIT RECORD AFTER SUCCESSFUL DEPLOY
    - name: Create Deployment Record
      if: success()
      run: |
        echo "Creating audit record with governance data:"
        echo "${{ env.GOVERNANCE_DATA }}"
        # Teams can optionally create their own audit records here